services:
  openmusic-api-backend:
    build: .
    container_name: openmusic-api-backend
    volumes:
      - /Users/ariss/Desktop/dicoding/belajar-fundamental-aplikasi-backend/Proyek Pertama/openmusic-api-v1:/app
    working_dir: /app
    command: sh -c "sleep 3 && npm run migrate up && nodemon ./src/server.js"
    ports:
      - 5000:5000
    depends_on:
      - db-openmusic-api
    networks:
      - openmusic-api-network

  db-openmusic-api:
    image: postgres
    container_name: db-openmusic-api
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=openmusic
    expose:
      - 5432
    networks:
      - openmusic-api-network
    volumes:
      - db-openmusic-api-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-db-openmusic-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db-openmusic-api
    networks:
      - openmusic-api-network

networks:
  openmusic-api-network:
    name: openmusic-api-network

volumes:
  db-openmusic-api-volume:
    name: db-openmusic-api-volume
